---
title: 'Exercise 2: R Markdown for Gapminder Exploration'
author: "Carleena Ortega"
date: "September 25 2019"
output: 
  github_document:
    toc: yes
always_allow_html: yes

---

```{r load, warning=FALSE, echo=FALSE} 
library(gapminder)
library(tibble)
library(DT)
library(tidyverse)
library(dplyr)
#should this be shown?
```

#Data on Gapminder
## Population of Countries
Here we show that gapminder has information on life expectancy, population, and GDP per capita of 142 countries from 1952
```{r}
str(gapminder)
```

## Summary of Gapminder Data

```{r}
summary(gapminder)
```

## Number of data collected per continent
<!--from summary we can find the number of entries per continent and we can use this to make vectors -->
```{r}
gapminder %>%
group_by(gapminder$continent)
counts<-n_distinct(gapminder$country)
plot(gapminder$continent,counts) #ggplots today
```

<!--plot(cont,datapt)--> #try to use gg plot
#use a unique fnc instead of making a vector for datapt (no penalty but good practice)

#use n_distinct to give the # of countries

