---
title: 'HW03: dplyr/ggplot2 Part II'
author: "Carleena Ortega"
date: "29/09/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages((library(dplyr)))
suppressPackageStartupMessages((library(ggplot2)))
suppressPackageStartupMessages((library(gapminder)))
```

# Instructions

Pick three of the six tasks below, and produce:

* a tibble, using dplyr as your data manipulation tool
* an accompanying plot of data from the tibble, using ggplot2 as your visualization tool
* some dialogue about what your tables/figures show (doesn’t have to be much).

Or, make up your own task(s)! If you want to do something comparable but different, i.e. swap one quantitative variable for another, be my guest! If you are feeling inspired and curious, then we’re doing this right. Go for it. Just write down the task that you are now doing. Between the dplyr coverage in class and the list below, I think you get the idea.


# Tasks

## Task Option 1
Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy – you decide – a mean or median or some other quantile or perhaps your current age. Then determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

## **Task Option 2**
Get the maximum and minimum of GDP per capita for all continents.

## **Task Option 3**
Look at the spread of GDP per capita within the continents.

## Task Option 4
Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

## **Task Option 5**
How is life expectancy changing over time on different continents?

## Task Option 6
Find countries with interesting stories. Open-ended and, therefore, hard. Promising but unsuccessful attempts are encouraged. This will generate interesting questions to follow up on in class.

